opentable/design-tokens

- .gitignore
- OTKit/otkit-colors/LICENSE
- OTKit/otkit-colors/colors.yml
- OTKit/otkit-colors/package.json
- OTKit/otkit-spacing/LICENSE
- OTKit/otkit-spacing/package.json
- OTKit/otkit-spacing/spacing.yml
- OTTheme/ottheme-colors/LICENSE
- OTTheme/ottheme-colors/colors.yml
- OTTheme/ottheme-colors/package.json
- OTTheme/ottheme-spacing/LICENSE
- OTTheme/ottheme-spacing/package.json
- OTTheme/ottheme-spacing/spacing.yml
- lerna.json
- package.json
- legacy: `ottheme-*`
- new: `otkit-*`
> [OC-66] Initialized repo with basic structure

- OTKit/otkit-colors/colors.yml
- OTKit/otkit-spacing/spacing.yml
This replaces #3 - adds comments, fixes up tabbing and adds required props.
Also adds all colors such as secondary, disabled etc.
> First pass at new colors

- OTKit/README.md
- OTKit/aliases.yml
- OTKit/otkit-colors/token.yml
- OTKit/otkit-spacing/token.yml
- OTTheme/README.md
- OTTheme/aliases.yml
- OTTheme/ottheme-colors/token.yml
- OTTheme/ottheme-spacing/token.yml
- README.md
- package.json
This addresses #7 #6 and add documentations for usage and contributions
> [OC-100] Aliases

- OTKit/README.md
- OTTheme/README.md
- README.md
> Docs updates

- OTKit/README.md
- README.md
- package.json
@lindseyhight @mannionaco I've published the typography token (OTKit), this PR to simply update the docs to reference it. 
I've added you as admins meaing you should be able to review/merge PR as well, I think this could be a good place to start 😃  (cc @lastquestion )
> Added docs for typography token and updated tools

- OTKit/aliases.yml
- OTKit/otkit-breakpoints/LICENSE
- OTKit/otkit-breakpoints/package.json
- OTKit/otkit-breakpoints/token.yml
When setting `width`, `height` and conditions for media queries, we want to avoid hard-coding the pixel values and instead have them live here as design tokens. Let me know what your thoughts are.
> introduced pixel value design tokens for layout of new restaurant profile

- OTTheme/aliases.yml
- OTTheme/ottheme-colors/token.yml
This is the primary blue color that is mainly used in Guest Center Admin
> Added Blue Malibu colour for Guest Centre Admin

- OTKit/aliases.yml
- OTKit/otkit-colors/token.yml
Secondary and primary are currently the same, pending new color from brand in future
> changed primary and secondary colors

- OTKit/aliases.yml
Update the following tokens:
- line-height-xsmall
- font-size-medium
- line-height-medium
- font-size-large
- line-height-large
> [PATCH] Updated font size and line heights

- OTKit/aliases.yml
Add color-white, a new design token. Mostly used for button text for timeslots and Button Primary.
> Add color-white: #FFFFFF

- OTKit/README.md
This PR improves the structure of README and adds instructions / gotchas on the publishing process.
https://opentable.atlassian.net/browse/RUSH-1123
> [RUSH-1123] Added instructions on publish

- OTKit/README.md
modify OTKit readme to make it a bit more friendly to designers
> RUSH-1123: modify readme to make it designer friendly

- OTTheme/aliases.yml
- OTTheme/ottheme-colors/token.yml
> [GLOBAL-146] - Add red colours

- OTKit/README.md
- OTKit/otkit-breakpoints/package.json
- OTKit/otkit-colors/package.json
- OTKit/otkit-desktop-typography/package.json
- OTKit/otkit-spacing/package.json
- OTKit/otkit-typography/package.json
- OTTheme/ottheme-colors/package.json
- OTTheme/ottheme-spacing/package.json
This should just make things easier
> Use the correct registry for publishing

- OTKit/aliases.yml
Adding the lightest gray color
cc @antwhite
> RUSH-1313: Add color-gray-active

- OTKit/aliases.yml
- OTKit/otkit-breakpoints/token.yml
- OTKit/otkit-colors/token.yml
- OTKit/otkit-spacing/token.yml
Previously discussed in https://github.com/opentable/design-tokens/issues/68.
> [MW-2038] Remove unnecessary aliasing.

- OTKit/otkit-spacing/token.yml
Accidentally added a spacing design token
> remove spacing-xxlarge

- OTKit/otkit-borders/LICENSE
- OTKit/otkit-borders/package.json
- OTKit/otkit-borders/token.yml
- OTKit/otkit-colors/package.json
- OTKit/otkit-desktop-typography/package.json
- OTKit/otkit-spacing/package.json
- OTKit/otkit-typography/package.json
- README.md
This PR introduces the borders token, which will store border related attributes, such as border radius, border width, border color, border style, etc. 
This PR just creates the token to lay the ground, we will work with designers to fill more values in there.
This PR also does some housekeeping:
- removes the last remaining personal developer info from author field;
- removes the homepage field in `package.json` because individual token doesn't have readme anymore;
- adjusts the order of tokens in main readme to be consistent with the alphabetical order of folders.
> [RUSH-1363] Borders token + housekeeping

- OTKit/otkit-shadows/LICENSE
- OTKit/otkit-shadows/package.json
- OTKit/otkit-shadows/token.yml
- README.md
This PR adds a new token to house text and box shadow values.
This PR just creates the token to lay the ground, we will work with designers to fill more values in there.
> [RUSH-983] Add new token to house text and box shadow values

- .gitignore
- package-lock.json
- style-guide/package-lock.json
- style-guide/package.json
- style-guide/src/pages/index.js
- style-guide/src/pages/otkit-desktop-typography.js
- style-guide/src/styles/example.module.css
- style-guide/src/styles/fonts.css
- style-guide/src/styles/otkit-desktop-typography.module.css
- Add lodash dependency
- Add global font face (Brandon Text)
- Display typography groupings
> Style guide: Initial typography styling

- package.json
Closes #100 
on a side-note: 🇮🇹 😆  for alphabetic ordering of scripts
> [DX-401] Prettier setup

- dependencies.yml
Closes #107 
Fixed path for the style-guide package, this should make the 🤖  😄
> [DX-400] Updated dependencies.yml

- package-lock.json
> artifactory => npm cleanup

- OTKit/otkit-breakpoints/token.yml
> [Major] Update token.yml

- OTKit/otkit-borders/package.json
- OTKit/otkit-shadows/package.json
2 tokens weren't published - this should do
> Fix versioning

- OTKit/otkit-breakpoints/token.yml
This PR adds the standardized set of breakpoints, we are seeing a lot of code duplications around the plus and minus 1 px, so let's add them and have them all organized here.
https://opentable.atlassian.net/browse/RUSH-1741
> [RUSH-1741] Standardize desktop, tablet and mobile breakpoints

- .gitignore
- OTKit/otkit-icons/.gitignore
- OTKit/otkit-icons/.npmignore
- OTKit/otkit-icons/package.json
- README.md
Super little PR to bring this in line with other repos in terms of gitignoring (one global rather than multiple) and npmignoring (using package.json)
> Housekeeping

- OTKit/otkit-icons/ic_checkbox.svg
> Checkbox fix

- style-guide/package.json
- style-guide/src/layouts/index.js
- style-guide/src/pages/index.js
- style-guide/src/pages/otkit-icons.js
- style-guide/src/styles/otkit-icons.module.css
Just a first go to see how it looks like /cc @lastquestion @francesyun @karuto @nickbalestra
> [DX-449] Integrate icons into the styleguide

- style-guide/src/components/section-header/styles.module.css
- style-guide/src/pages/index.js
- style-guide/src/pages/otkit-typography.js
- style-guide/src/styles/tokens.module.css
Follows #145 
I also added a title in the home:
> [DX-458] Update styleguide to reflect new naming conventions

- package.json
- utils/automatic-release/index.js
- utils/automatic-release/process.js
- utils/automatic-release/test/process.test.js
So that we can run it on branches that are not master
> Adding a --test flag to the automatic release script

- .travis.yml
- utils/automatic-release/process.js
We still need to add the proper npm-token to the travis cofniguration. 
I've chatted with @MaximeDevalland and will pair for him to do that, once that is done we should be able to merge this and automatic-publishing should then be enabled.
> [DX-457] Travis Setup for automatic-release

- package.json
- style-guide/package.json
- utils/deploy-styleguide/index.js
Tested locally and worked.
After we can cleanup and remove some scripts, add some more tests and close this ticket
> Programmatic gh-pages deploy script

- CONTRIBUTING.md
- README.md
- package.json
- utils/automatic-release/lib/publishPackage.js
- utils/automatic-release/test/__snapshots__/process.test.js.snap
This should close the story for all the automatic release of tokens and the continuos deployment of the styleguide
> [DX-457] Auto release cleanup

- OTKit/otkit-colors/token.yml
We have updated colors -- slightly bluer than before. Shouldn't break anything.
> update to new colors

- OTKit/otkit-ticketing-desktop/LICENSE
- OTKit/otkit-ticketing-desktop/package.json
- OTKit/otkit-ticketing-desktop/token.yml
This PR introduces the first "functional token" (issue https://github.com/opentable/design-tokens/issues/91) that's intended to capture all the design decisions about a specific user experience segment / product: ticketing experience on desktop web. The design decisions originated from @francesyun. 😇 
In V1 it will only be used for ticketing modal that I developed. In time, we would like this to be shared across other desktop web ticketing experience products, such as booking flow and rest ref segments. 
The ticketing modal CSS is already 95% design tokens, therefore this token only captures design decisions that are NOT present in other universal tokens. Let me know what you think of this approach.
The variable names are self explanatory enough. I'm very flexible with the naming …
> Functional token for ticketing experience on desktop web

- OTKit/otkit-colors/package.json
- OTKit/otkit-icons/package.json
- OTKit/otkit-ticketing-desktop/package.json
- OTTheme/ottheme-colors/package.json
- OTTheme/ottheme-spacing/package.json
- utils/automatic-release/lib/installPackages.js
- utils/automatic-release/lib/process.js
- utils/automatic-release/lib/publishPackage.js
returning all the promises and running mapSeries to avoid the script to publish what should be not published
> [DX-473] Fix build

- .travis.yml
This is Part I for the work we are doing to move github/npm integration on travis from Nick's user to an ops owned user (opentable-devops).
For the time being, I moved these vars in Travis so that we can test before moving to the other user.
> [DX-475] Use travis variables for anything regarding the user

- dependencies.yml
as discussed with @nickbalestra
> Fixes on dependencies.io config

- OTKit/otkit-typography-desktop/token.yml
this is to support use cases within the restaurant product. design approved.
> adding large-medium and small-bold

- style-guide/package.json
dependencies.io runs daily and should perform this, but I wanted to speed up this so that we can have a working styleguide.
> [DX-527] Use latest colors

- OTKit/otkit-colors/token.yml
- Fixed some alphabetizing
- added white
> Alphabetize color tokens, add white

- OTKit/otkit-typography-desktop/token.yml
xlarge 32px to 28px, line-height 40px to 36px
large 24px to 22px, line-height 32px to 28px
> updating xlarge and large

- OTKit/otkit-icons/ic_indeterminate.svg
from ic_indeterminate to ic_checkbox_indeterminate
> modifying name

- OTKit/otkit-spacing/token.yml
Adding 48px as xlarge spacing unit, changing 64px from xlarge to xxlarge
> Adding spacing unit

- style-guide/src/pages/otkit-typography.js
@benaz23 this should fix your issue of some latest values missing in the style guide.
> Update typography style guide to reflect changes

- style-guide/src/components/section-header/styles.module.scss
- style-guide/src/styles/fonts.module.scss
- style-guide/src/styles/index.module.scss
- style-guide/src/styles/otkit-colors.module.scss
- style-guide/src/styles/otkit-icons.module.scss
- style-guide/src/styles/otkit-typography-desktop.module.scss
Adds missing scss that was causing a failing styleguide build. Thanks @ronniechong for diagnosing!
> fix(style-guide): add missing scss

- style-guide/src/components/layout/layout.js
- style-guide/src/styles/index.module.scss
> feat(style-guide): Teal styling to Design tokens page

- OTKit/otkit-icons/ic_messaging.svg
This PR adds a new icon called `ic_messaging`
> feat(otkit-icons): adds ic_messaging
