opentable/design-tokens

.gitignore, OTKit/otkit-colors/package.json, OTKit/otkit-spacing/package.json, OTTheme/ottheme-colors/package.json, OTTheme/ottheme-spacing/package.json, README.md, tools/theo-cli/README.md, tools/theo-cli/scripts/build.js
- added minor left out on the various packages in preparation for publishing
- bette defaults for the build so consuming will look like `require('otkit-spacing/token.cssmodules.css')` (no need for a `dist/`)
=> Minor adjustements

OTKit/README.md
This PR primarily aims to resolve some confusion around `save-dev` in the current OTKit documentation. It also includes some very minor typo and formatting fixes.
Going forward I plan to continue polishing and adding to the documentations as we develop more with design tokens.
https://opentable.atlassian.net/browse/RUSH-792
=> [RUSH-792] Improve documentation of OTKit around save-dev, minor fixes

OTKit/otkit-typography/LICENSE, OTKit/otkit-typography/package.json, OTKit/otkit-typography/token.yml
@lastquestion I've created a scaffholding for the typography token.
When working on it, please rely on the [aliases](https://github.com/opentable/design-tokens/blob/master/OTKit/aliases.yml) file for storing all alias/value and then use those within the token itself. 
This allows for non duplicating and reuse of values among tokens if/when needed. (spacing and colors already rely on it). It also make for designer even easier as they most probably want to focus their work on that file first. If you need anything, please do let me know.
=> [OC-92] Typography token

OTKit/aliases.yml, OTKit/otkit-typography/token.yml
This PR changes the type of `font-weight-medium` to a number instead of string, so that value "500" can be parsed by Theo correctly without quotation marks around. This will ensure font weight is properly calculated in start page.
The only real line of change is the "type". All others seem to be auto indentation fixes by running the `npm run build`.
https://opentable.atlassian.net/browse/RUSH-869
=> RUSH-869 Change type of 'font-weight-medium' to number

OTTheme/ottheme-colors/token.yml
`darken-percent` was wrongly converted to a color, while should be type `number`.
=> [DX-159] Type fix

OTKit/README.md, OTKit/otkit-typography/token.yml
This PR changes the type of `font-weight-normal` and `font-weight-bold` to a special "raw" type instead of string, so that values can be parsed by Theo correctly without quotation marks around. This will ensure font weight is properly calculated in start page.
Browser won't be able to parse it if type is "string":
This PR also adds some documentation on how to preview and debug a token's generated values.
Theo, the design token parser we use, has a preset of types that each maps to a special transformer to do processing. For example, type `string` adds quotation marks around, type `color` does RGBA format conversion, etc. The new type I defined here, `raw` is actually NOT in the supported Theo transformer list, which means it will preserve the value as is, achieving what we wanted. …
=> RUSH-1085 Fix types of font weights, add docs about preview & debug

OTKit/otkit-breakpoints/token.yml, OTKit/otkit-colors/token.yml, OTKit/otkit-desktop-typography/package.json, OTKit/otkit-desktop-typography/token.yml, OTKit/otkit-spacing/token.yml, OTKit/otkit-typography/token.yml
This PR is taking over https://github.com/opentable/design-tokens/pull/48 so I will paste the original description below.
These typography style groupings are based on Kellen's design spec: https://opentable.invisionapp.com/boards/SP3ARCZNYQXEK/ 
This PR is based on @lastquestion's PR https://github.com/opentable/design-tokens/pull/32. The discussion related to this ticket can be found [here](https://github.com/opentable/design-tokens/issues/26).
The purpose of this PR is to introduce a batch of platform specific values that are composed of the "original", platform agnostic values.
The start page implementation can be found here: https://github.com/opentable/start-page-nodejs/pull/3056, check out its description and comments for more context. …
=> [RUSH-886] Added OTKit desktop web typography token, added platform metadata

OTKit/otkit-desktop-typography/LICENSE, OTKit/otkit-desktop-typography/token.yml, README.md
This PR adds the new token to README (it existed since #64).
This PR also adds the missing license file.
=> Added otkit-desktop-typography readme & license

OTKit/otkit-colors/token.yml
This PR is replacing https://github.com/opentable/design-tokens/pull/54, originally proposed by @francesyun. I recreated this PR because the infrastructure has changed considerably since then.
Here's her original description:
- Deleted color-primary-disabled in aliases.yml, as it doesn't have it's own independent value (it is equivalent to color-gray-secondary). Developers can still use the variable under its new definition, as defined in token.yml in otkit-colors.
- Updated color-primary-active. The hex value was out of date.
=> [MAJOR] Deleted color-primary-disabled, use color-gray-secondary

OTKit/otkit-colors/token.yml
Changing the hex value of color-primary-active to match the hover-state of buttons that was used in the previous OpenTable design to align with the rest of the website.
=> changing color-primary-active

OTKit/otkit-colors/package.json, OTKit/otkit-desktop-typography/package.json, OTKit/otkit-spacing/package.json, OTKit/otkit-typography/package.json, OTTheme/ottheme-colors/package.json, OTTheme/ottheme-spacing/package.json
This PR replaces developers' personal details with the official communal group account for design tokens.
Motivation: some of our contributors feels uncomfortable putting personal information in the author field of a company-owned open sourced project.
Analysis: we overall support the decision to remove personal details from these tokens, because:
- Design tokens encourage collaboration and shared ownership; a pool of community contributors help to make each token better, having a singular author doesn't represent (and discourages) this reality;
- This author info gets outdated once that person decided to not get involved with this project anymore, or even worse, leave the company; this could be a liability concern down the road;
- None of the other prominent design token systems …
=> [HOUSEKEEPING] Replace personal details with official communal group account

.gitignore, _config.yml, docs/README.md, docs/_config.yml, lerna.json, package.json, style-guide/README.md, style-guide/gatsby-config.js, style-guide/package.json, style-guide/src/pages/index.js, style-guide/src/pages/otkit-desktop-typography.js, style-guide/src/styles/example.module.css, style-guide/src/styles/index.module.css
Closes #94 
This PR cover the following:
- grouping token to be discussed & implemented - for @karuto
=> [DX-397] Style guide alt

dependencies.yml
Closes #98 
Added dependencies.io configured for this lerna monorepo so that we'll get PRs everytime a dependency could be updated, this allow us to keep the repo and the tools we use in it, up-to-date effortless
=> [DX-400] Dependencies.io config

style-guide/src/pages/index.js
We are going to have platform switch support inside specific token files, so we are going to name this just a generic "typography" and later add more.
=> Fix reference to style guide js file

style-guide/src/components/section-header/styles.module.css, style-guide/src/styles/fonts.module.css, style-guide/src/styles/index.module.css, style-guide/src/styles/otkit-colors.module.css, style-guide/src/styles/otkit-typography-desktop.module.css, style-guide/src/styles/tokens.module.css
Closes #134 
Gatsby fails to compile the styleguide when referencing multiple times the css modules from different source with a `Error: Order in extracted chunk undefined` exception (only on build, not during develop).
The best way to fix it is to hook into the extract-text-webpack-plugin config and use the `ignoreOrder` option ([reference](https://github.com/webpack-contrib/extract-text-webpack-plugin#options)). Unfortunately, Gatsby still uses webpack 1 with an old version and the work towards webpack 3 (4?) is still ongoing: https://github.com/gatsbyjs/gatsby/projects/2
An hack that I found to avoid the issue to happen is by removing circular dependencies and just flattening the tree by having a single file referencing all the tokens, and then using that inside the various css …
=> [DX-448] Group all the tokens references to a single file

OTKit/otkit-typography-desktop/token.yml
This PR updates the desktop typography token based on @mannionaco's changes in the latest symbol library, including the `xlarge` and `xxlarge` changes mentioned in #97, which I'm closing in favor of this PR.
This is a breaking change and would require major version update. @mannionaco and @francesyun have reached an agreement on the naming convention at least on the desktop web.
The changset may be confusing, I recommend using split mode or viewing the file directly.
- We are removing aliases from typography tokens, so that each of the platform has a holistic local source of truth that is clearly visible to designers. This allows us to evolve each platform faster without worrying about shared values and deltas. For more context behind this decision see …
=> Update desktop typography based on latest symbol library

utils/automatic-release/lib/installPackages.js, utils/automatic-release/lib/process.js, utils/automatic-release/test/process.test.js
1) When the token was unpublished, npm install would 404 and there would be a mess of events on the cmd.on('close') because of this: https://nodejs.org/api/child_process.html#child_process_event_close. More specifically *This is distinct from the 'exit' event, since multiple processes might share the same stdio streams*. The way I fixed it is by doing the same action is sequence.
2) There was also a "undefined" on the err diff, which I replaced with <DIFF NOT AVAILABLE> which is imho cleaner.
=> [DX-473] Auto-publish fails when there is a new token (fix)

OTKit/otkit-colors/token.yml, style-guide/src/components/section-header/styles.module.css, style-guide/src/pages/otkit-colors.js, style-guide/src/styles/index.module.css, style-guide/src/styles/otkit-colors.module.css, style-guide/src/styles/otkit-icons.module.css, style-guide/src/styles/tokens.module.css
1. Implement the new colors, as per design. This adds colors that are named by content, not by intent. There is a mapping of old to new colors, which I will add to a comment below this PR description.
2. Group the colors by their base color.
3. Fix all the incorrect references to token values that were renamed, lost, changed, etc. In particular `typography` stuff was renamed and no one fixed the styleguide.
I want to figure out a way to throw errors when building for the variables thing, but I'll do that in a follow up PR.
=> [breaking change] new colors; fix styleguide

OTKit/otkit-icons/package.json
So the version that is published is 3.0.0 (as well as 2.1.0), but because of racing, the actual package.json wasn't updated, so... updating it manually to 3. As this merges, it should bump to 3.1.0 - I think - based on what has changed. The failed publishes in master are trying to do a minor bump right now.
the next icon PR #229 will be a breaking change without actual content changing, so I will manually bump to 4.0.0 and publish that manually, and then we should be back to normal with autopublishes.
=> fix version of otkit-icons to match what is published

style-guide/package.json
Fix the styleguide dependency with a major bump to get the styleguide to build properly so the automation is green. Prepares us to go to v4.
=> fix styleguide build for v3 icons

OTKit/otkit-icons/package.json
cc @jrolfs @acolchado @karuto 
So, I was about to publish otkit-icons@4.0.0, when I discovered - by luckily hand running dry-run publish - that we are not publishing the commonjs.
Also, I notice that the cssmodule and SASS versions of the icons would have a giant full SVG XML markup, without enclosing `"` quotes.
For now, I would like to move forward by only outputting commonjs, and not the other versions for now. We can support the other versions in a patch followup by customizing the output to be a data-uri via adding custom code to the theo generation.
Right now, the build steps are still disabled in travis. We should merge this to master, then I can publish v4 and then push the tags and commit to master, and then reenable the build.
=> only generate commonjs for otkit-icons for now

OTKit/otkit-typography-desktop/token.yml
This new grouping is added based on @mannionaco's latest spec. We may change the name later. This will also get the auto publishing bot to rebuild the typography-desktop token and fix the empty package bug we had with version 3.0.0.
=> Add xxsmall-regular aka footnote typography grouping

style-guide/package.json
Reverts opentable/design-tokens#333, which broke **master**
=> Revert "Update gatsby in style-guide/package.json from ^1.9.199 to ^2.0.44"

style-guide/src/pages/otkit-typography.js
This PR adds a paragraph advertising `@ot-react-ui/typography-desktop` package for the potential consumers of the `typography-desktop` token.
=> Add @ot-react-ui/typography-desktop to Design Bar

style-guide/package.json
This PR updates the Design Bar style guide typography section to the latest version.
=> Update otkit-typography-desktop in style-guide/package.json from ^2.0.0 to ^3.1.0

OTKit/otkit-colors/token.yml
As #255 pointed out, we spelled "fuchsia" wrong for the longest time. This corrects it, but I would like to make sure that we spell it right in the design tools as well. @mannionaco 
This will be a breaking change, requiring a major version update.
=> Update fuchsia typo

style-guide/package.json
The current style guide is outdated when it comes to icons & colors. This brings it up to spec.
cc @mannionaco @benaz23 🙇
=> Update Design Bar to use latest otkit-icons v7 and otkit-colors v4

OTKit/otkit-typography-desktop/token.yml
cc @Kimtaro 
Let's add the japanese language font stack to the design tokens for desktop typography so we can use them everywhere and don't need to copy and paste.
=> add japanese language font statck

OTKit/otkit-icons/ic_setting.svg
=> fix(otkit-icons): removes ic_setting because wrong filename

OTKit/otkit-icons/ic_setting.svg
Reverts opentable/design-tokens#471
=> Revert "fix(otkit-icons): removes ic_setting because wrong filename"

OTKit/otkit-icons/ic_warning.svg
Add `ic_waring` icon to design token
In design token, we have `ic_warning_timeline` - . But the icon size not match other icons. 
Not sure the user who use it.  @yuebwang sent me the one from design system
=> feat(otkit-icons): add ic_warning icon

OTKit/otkit-typography-desktop/token.yml
This PR updating the two font sets: `large-bold` and `xlarge-bold` to reflect to the new OTKit changes.
The fonts updates:
`large-bold` from `22px` to `24px`
`xlarge-bold` from `28px` to `32px`
Line heights and font weights remain the same.
This is a `patch` upgrade unless we need to go minor.
Jira ticket: [BUF-48](https://opentable.atlassian.net/browse/BUF-48)
=> fix(otkit-typography-desktop): BUF-48 updates large and xlarge bold font sizes

OTKit/otkit-icons/package.json
This PR is to include the icon token support for css modules. Somehow we have been publishing the NPM packages to include common js and scss only. This has been happening for a while now because Travis build always output false positives on the builds.
[https://api.travis-ci.org/v3/job/675835661/log.txt](https://api.travis-ci.org/v3/job/675835661/log.txt)
The css modules was ignore because npmjs is using `gitignore` as substitute.
[https://docs.npmjs.com/files/package.json#files](https://docs.npmjs.com/files/package.json#files)
=> fix(otkit-icons): include css modules file

style-guide/package.json
This PR is bumping the version for `otkit-icons`. I am trying to resolve the older package which is trying to look for the cssmodules and it does not exist in previous versions
=> fix(styleguide): bumps version for styleguide otkit-icons

README.md, style-guide/package.json, style-guide/src/components/section-header/index.js, style-guide/src/components/section-header/styles.module.css, style-guide/src/layouts/index.js, style-guide/src/pages/index.js, style-guide/src/pages/otkit-icons-theme.js
This PR adds a themeable icons styleguide/docs in the Github pages (https://opentable.github.io/design-tokens/otkit-icons/)
=> feat(styleguide): adds themeable icon styleguide

OTKit/otkit-typography-desktop/token.yml
A font size of 10px is needed for the OTKit Badge  in Figma https://www.figma.com/file/5oTMsfo42hZrlxvMraGmGd/OTKit---Web?node-id=2608%3A1389
=> [LOL-1571] Adding xxxsmall font size

OTKit/otkit-typography-desktop/token.yml
we're missing `xxsmall-medium` font size, weight and line height. Need it for this PR https://github.com/opentable/buffet/pull/2652
[OTK-143](https://opentable.atlassian.net/browse/OTK-143)
=> [OTK-143] update otkit-typography-desktop - add xxsmallmedium font
